### PR TITLE
Added $sub_url to tutor_dashboard_url filter

### PR DESCRIPTION
**Pull request by w3guy**
CC @shewa12 @sifat009 @harunollyo

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
@shewa12 @sifat009 @harunollyo, looks OK, if it allowed to add now arguments to existing filters - is this fine? Thanks!

**Comment by harunollyo** [comment]
PR to master not allowed

**Comment by w3guy** [comment]
@harunollyo how then do I submit a PR? against which branch?

This PR is important to us though.

**Comment by w3guy** [comment]
This is a really simple change that is backward compatible. 

CC @shewa12 @sifat009 @harunollyo

**Comment by bernhardkaindl** [comment]
@w3guy, it seems that PR should be based on dev and be opened against dev

**Comment by w3guy** [comment]
@bernhardkaindl @shewa12 @sifat009 @harunollyo I am unable to create a PR against the dev branch. I don't have such permission. Here's my fork https://github.com/w3guy/tutor/commit/40bc7cc3b5c4ccbe0762e5cbf4c101881c595f59

Could you guys please manually include this change to Tutor?

**Comment by bernhardkaindl** [comment]
@w3guy opened #522 for you.

I tried to reopen your branch from your repo, but that was denied, but opening from my repo was no problem.

However it's quite a hustle to have to remember to switch to the dev branch when opening a PR.

It would be far better if dev would be the default branch.

@shewa12, @sifat009 could you make dev the default branch for merge requests?

**Comment by w3guy** [comment]
@bernhardkaindl thank you.

**Pull request closed without merging**
