### PR TITLE
Added filter to logout redirect URL

### PR DESCRIPTION
**Pull request by w3guy**
Cc @jayedul @hsntareq @sifat009

### CODE REVIEW

**Comment by w3guy** [comment]
Can we get this added to Tutor now 2.0 is out? Cc @jayedul @hsntareq @sifat009

**Comment by jayedul** [comment]
I didn’t find any usage of this method in Tutor LMS. It seems redundant. Are you using it in any custom made plugin or theme?

**Comment by jayedul** [comment]
Ok, it will be merged in v2.0.2
Currently released version is 2.0.1

**Comment by jayedul** [comment]
Merged with development codebase.

**Comment by w3guy** [comment]
@jayedul just to be sure this was successfully done, please share a link to the commit with this change. Please

**Comment by jayedul** [comment]
https://github.com/themeum/tutor/commit/a84b528376a19adf07accc16eba844f51d184ab3

**Comment by w3guy** [comment]
What about #71 and #72 ?

Please confirm they've been added too @jayedul

**Comment by jayedul** [comment]
Merged both. **dev** branch updated.

**Pull request closed without merging**
